version: "3"
services:
  exercise5:
    build: .
    ports:
      - "9001:9001"
    links:
      - mongodb
      - replica
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  replica:
    image: mongo
    volumes:
      - ./data/db2:/data/db
    ports:
      - 27018:27017
