version: "3"
services:
  exercise6:
    build: .
    ports:
      - "9006:9006"
    links:
      - messageapp
      - mongodb
      - replica
      - redis
    depends_on:
      - messageapp
      - mongodb
      - replica
      - redis
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  replica:
    image: mongo
    volumes:
      - ./data/replica:/data/db
    ports:
      - 27018:27017
  redis:
    image: redis
    ports:
      - 6379:6379