version: "3"
services:
  exercise3:
    build: .
    ports:
      - "9001:9001"
    links:
      - messageapp
      - mongodb
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongodb2:
    image: mongo
    volumes:
      - ./data2/db:/data/db
    ports:
      - 27018:27017